/**
 * JWTToken_Auth_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfile { 
    id?: number;
    userId?: number;
    profilePictureUrl?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    adress?: string | null;
    dateOfBirth?: string | null;
}

